export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_FROM_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const MINUS_QUANTITY = "MINUS_QUANTITY";
export const UPDATE_ITEMS_FROM_CART = "UPDATE_ITEMS_FROM_CART";
